43FROM node:20-alpine AS client-build

WORKDIR /build

COPY client/package*.json ./
RUN npm ci

COPY client/ ./
RUN npm run build

FROM nginx:alpine

COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY --from=client-build /build/build /usr/share/nginx/html
